namespace DistanceCalCulator
{
    partial class SearchSetting
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.comboBox3 = new System.Windows.Forms.ComboBox();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.comboBox3);
            this.groupBox1.Controls.Add(this.comboBox2);
            this.groupBox1.Controls.Add(this.comboBox1);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new System.Drawing.Point(12, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(301, 267);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Apply Database Filters";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(20, 37);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(71, 18);
            this.label1.TabIndex = 0;
            this.label1.Text = "Continent";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(20, 69);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(60, 18);
            this.label2.TabIndex = 1;
            this.label2.Text = "Country";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(20, 107);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(55, 18);
            this.label3.TabIndex = 2;
            this.label3.Text = "Region";
            // 
            // comboBox1
            // 
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "All",
            "Africa   (AF)",
            "Asia      (AS)",
            "Europe (EU)",
            "Nort America   (NA)",
            "South America (SA)",
            "Australia  (OC)"});
            this.comboBox1.Location = new System.Drawing.Point(111, 34);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(121, 21);
            this.comboBox1.TabIndex = 3;
            // 
            // comboBox2
            // 
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Items.AddRange(new object[] {
            "All",
            "Andorra",
            "United Arab Emirates",
            "Afghanistan",
            "Antigua and Barbuda",
            "Anguilla",
            "Albania",
            "Armenia",
            "Angola",
            "Antarctica",
            "Argentina",
            "American Samoa",
            "Austria",
            "Australia",
            "Aruba",
            "Azerbaijan",
            "Bosnia and Herzegovina",
            "Barbados",
            "Bangladesh",
            "Belgium",
            "Burkina Faso",
            "Bulgaria",
            "Bahrain",
            "Burundi",
            "Benin",
            "Saint BarthÃ©lemy",
            "Bermuda",
            "Brunei",
            "Bolivia",
            "Caribbean Netherlands",
            "Brazil",
            "Bahamas",
            "Bhutan",
            "Botswana",
            "Belarus",
            "Belize",
            "Canada",
            "Cocos (Keeling) Islands",
            "Congo (Kinshasa)",
            "Central African Republic",
            "Congo (Brazzaville)",
            "Switzerland",
            "CÃ´te d\'Ivoire",
            "Cook Islands",
            "Chile",
            "Cameroon",
            "China",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Cape Verde",
            "CuraÃ§ao",
            "Christmas Island",
            "Cyprus",
            "Czech Republic",
            "Germany",
            "Djibouti",
            "Denmark",
            "Dominica",
            "Dominican Republic",
            "Algeria",
            "Ecuador",
            "Estonia",
            "Egypt",
            "Western Sahara",
            "Eritrea",
            "Spain",
            "Ethiopia",
            "Finland",
            "Fiji",
            "Falkland Islands",
            "Micronesia",
            "Faroe Islands",
            "France",
            "Gabon",
            "United Kingdom",
            "Grenada",
            "Georgia",
            "French Guiana",
            "Guernsey",
            "Ghana",
            "Gibraltar",
            "Greenland",
            "Gambia",
            "Guinea",
            "Guadeloupe",
            "Equatorial Guinea",
            "Greece",
            "South Georgia and the South Sandwich Islands",
            "Guatemala",
            "Guam",
            "Guinea-Bissau",
            "Guyana",
            "Hong Kong",
            "Honduras",
            "Croatia",
            "Haiti",
            "Hungary",
            "Indonesia",
            "Ireland",
            "Israel",
            "Isle of Man",
            "India",
            "British Indian Ocean Territory",
            "Iraq",
            "Iran",
            "Iceland",
            "Italy",
            "Jersey",
            "Jamaica",
            "Jordan",
            "Japan",
            "Kenya",
            "Kyrgyzstan",
            "Cambodia",
            "Kiribati",
            "Comoros",
            "Saint Kitts and Nevis",
            "North Korea",
            "South Korea",
            "Kosovo",
            "Kuwait",
            "Cayman Islands",
            "Kazakhstan",
            "Laos",
            "Lebanon",
            "Saint Lucia",
            "Liechtenstein",
            "Sri Lanka",
            "Liberia",
            "Lesotho",
            "Lithuania",
            "Luxembourg",
            "Latvia",
            "Libya",
            "Morocco",
            "Monaco",
            "Moldova",
            "Montenegro",
            "Saint Martin",
            "Madagascar",
            "Marshall Islands",
            "Macedonia",
            "Mali",
            "Burma",
            "Mongolia",
            "Macau",
            "Northern Mariana Islands",
            "Martinique",
            "Mauritania",
            "Montserrat",
            "Malta",
            "Mauritius",
            "Maldives",
            "Malawi",
            "Mexico",
            "Malaysia",
            "Mozambique",
            "Namibia",
            "New Caledonia",
            "Niger",
            "Norfolk Island",
            "Nigeria",
            "Nicaragua",
            "Netherlands",
            "Norway",
            "Nepal",
            "Nauru",
            "Niue",
            "New Zealand",
            "Oman",
            "Panama",
            "PerÃº",
            "French Polynesia",
            "Papua New Guinea",
            "Philippines",
            "Pakistan",
            "Poland",
            "Saint Pierre and Miquelon",
            "Pitcairn",
            "Puerto Rico",
            "Palestinian Territory",
            "Portugal",
            "Palau",
            "Paraguay",
            "Qatar",
            "RÃ©union",
            "Romania",
            "Serbia",
            "Russia",
            "Rwanda",
            "Saudi Arabia",
            "Solomon Islands",
            "Seychelles",
            "Sudan",
            "Sweden",
            "Singapore",
            "Saint Helena",
            "Slovenia",
            "Slovakia",
            "Sierra Leone",
            "San Marino",
            "Senegal",
            "Somalia",
            "Suriname",
            "South Sudan",
            "SÃ£o TomÃ© and Principe",
            "El Salvador",
            "Sint Maarten",
            "Syria",
            "Swaziland",
            "Turks and Caicos Islands",
            "Chad",
            "French Southern Territories",
            "Togo",
            "Thailand",
            "Tajikistan",
            "Tokelau",
            "Timor-Leste",
            "Turkmenistan",
            "Tunisia",
            "Tonga",
            "Turkey",
            "Trinidad and Tobago",
            "Tuvalu",
            "Taiwan",
            "Tanzania",
            "Ukraine",
            "Uganda",
            "United States Minor Outlying Islands",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vatican City",
            "Saint Vincent and the Grenadines",
            "Venezuela",
            "British Virgin Islands",
            "U.S. Virgin Islands",
            "Vietnam",
            "Vanuatu",
            "Wallis and Futuna",
            "Samoa",
            "Yemen",
            "Mayotte",
            "South Africa",
            "Zambia",
            "Zimbabwe",
            "Unknown or unassigned country"});
            this.comboBox2.Location = new System.Drawing.Point(111, 70);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new System.Drawing.Size(121, 21);
            this.comboBox2.TabIndex = 4;
            // 
            // comboBox3
            // 
            this.comboBox3.FormattingEnabled = true;
            this.comboBox3.Items.AddRange(new object[] {
            "All",
            "Bengo Province",
            "Benguela Province",
            "BiÃ© Province",
            "Cabinda Province",
            "Cuando Cubango Province",
            "Cuanza Norte Province",
            "Cuanza Sul Province",
            "Cunene Province",
            "HuÃ­la Province",
            "Huambo Province",
            "Luanda Province",
            "Lunda Norte Province",
            "Lunda Sul Province",
            "Malanje Province",
            "Moxico Province",
            "Namibe Province",
            "UÃ­ge Province",
            "Zaire Province",
            "(unassigned)",
            "Bale",
            "Bam",
            "Banwa",
            "Bazega",
            "Bougouriba",
            "Boulgou",
            "Boulkiemde",
            "Comoe",
            "Ganzourgou",
            "Gnagna",
            "Gourma",
            "Houet",
            "Ioba",
            "Kadiogo",
            "Kenedougou",
            "Komondjari",
            "Kompienga",
            "Kossi",
            "Koulpulogo",
            "Kouritenga",
            "Kourweogo",
            "Leraba",
            "Loroum",
            "Mouhoun",
            "Nahouri",
            "Namentenga",
            "Nayala",
            "Noumbiel",
            "Oubritenga",
            "Oudalan",
            "Passore",
            "Poni",
            "Sanguie",
            "Sanmatenga",
            "Seno",
            "Siasili",
            "Soum",
            "Sourou",
            "Tapoa",
            "Tui",
            "Yagha",
            "Yatenga",
            "Ziro",
            "Zondoma",
            "Zoundweogo",
            "(unassigned)",
            "Bubanza",
            "Bujumbura",
            "Bururi",
            "Cankuzo",
            "Cibitoke",
            "Gitega",
            "Karuzi",
            "Kayanza",
            "Makamba",
            "Muramvya",
            "Mwaro",
            "Ngozi",
            "Rutana",
            "Ruyigi",
            "(unassigned)",
            "Alibori",
            "Atakora",
            "Atlantique",
            "Borgou",
            "Collines",
            "Donga",
            "Kouffo",
            "Littoral",
            "Mono",
            "Oueme",
            "Plateau",
            "Zou",
            "(unassigned)",
            "Central District",
            "Ghanzi District",
            "Kgalagadi District",
            "Kgatleng District",
            "Kweneng District",
            "North-East District",
            "North-West District",
            "South-East District",
            "Southern District",
            "(unassigned)",
            "Bandundu",
            "Bas-Congo",
            "Equateur",
            "Haut-Congo",
            "Kasai-Occidental",
            "Kasai-Oriental",
            "Katanga",
            "Kinshasa",
            "Maniema",
            "Nord-Kivu",
            "Orientale",
            "Sud-Kivu",
            "(unassigned)",
            "Bamingui-Bangoran",
            "Bangui",
            "Basse-Kotto",
            "Haute-Kotto",
            "Haut-Mbomou",
            "KÃ©mo",
            "Lobaye",
            "MambÃ©rÃ©-KadÃ©Ã¯",
            "Mbomou",
            "Nana-GrÃ©bizi",
            "Nana-MambÃ©rÃ©",
            "Ombella-M\'Poko",
            "Ouaka",
            "Ouham",
            "Ouham-PendÃ©",
            "Sangha-MbaÃ©rÃ©",
            "Vakaga",
            "(unassigned)",
            "Bouenza",
            "Brazzaville",
            "Cuvette",
            "Cuvette-Ouest",
            "Kouilou",
            "Lekoumou",
            "Likouala",
            "Niari",
            "Plateaux",
            "Pool",
            "Sangha",
            "(unassigned)",
            "AgnÃ©by",
            "Bafing",
            "Bas-Sassandra",
            "DenguÃ©lÃ©",
            "Dix-Huit Montagnes",
            "Fromager",
            "Haut-Sassandra",
            "Lacs",
            "Lagunes",
            "MarahouÃ©",
            "Moyen-Cavally",
            "Moyen-ComoÃ©",
            "N\'zi-ComoÃ©",
            "Savanes",
            "Sud-Bandama",
            "Sud-ComoÃ©",
            "VallÃ©e du Bandama",
            "Worodouqou",
            "Zanzan",
            "(unassigned)",
            "Adamaoua Region",
            "Centre Region",
            "East Region",
            "Far North Region",
            "Littoral Region",
            "North Region",
            "North-West Region",
            "South Region",
            "South-West Region",
            "West Region",
            "(unassigned)",
            "Barlavento Islands",
            "Sotavento Islands",
            "(unassigned)",
            "Ali Sabiah",
            "Arta",
            "Dikhil",
            "Djibouti",
            "Obock",
            "Tadjoura",
            "(unassigned)",
            "AÃ¯n Defla Province",
            "AÃ¯n TÃ©mouchent Province",
            "Adrar Province",
            "Algiers Province",
            "Annaba Province",
            "BÃ©char Province",
            "BÃ©jaÃ¯a Province",
            "Batna Province",
            "Biskra Province",
            "Blida Province",
            "Bordj Bou ArrÃ©ridj Province",
            "Bouira Province",
            "BoumerdÃ¨s Province",
            "Chlef Province",
            "Constantine Province",
            "Djelfa Province",
            "El Bayadh Province",
            "El Oued Province",
            "El Tarf Province",
            "GhardaÃ¯a Province",
            "Guelma Province",
            "Illizi Province",
            "Jijel Province",
            "Khenchela Province",
            "Laghouat Province",
            "MÃ©dÃ©a Province",
            "Mascara Province",
            "Mila Province",
            "Mostaganem Province",
            "M\'Sila Province",
            "Naama Province",
            "Oran Province",
            "Ouargla Province",
            "Oum el Bouaghi Province",
            "Relizane Province",
            "SÃ©tif Province",
            "SaÃ¯da Province",
            "Sidi Bel Abbes Province",
            "Skikda Province",
            "Souk Ahras Province",
            "TÃ©bessa Province",
            "Tamanghasset Province",
            "Tiaret Province",
            "Tindouf Province",
            "Tipaza Province",
            "Tissemsilt Province",
            "Tizi Ouzou Province",
            "Tlemcen Province",
            "(unassigned)",
            "Alexandria Governorate",
            "Aswan Governorate",
            "Asyut Governorate",
            "Beheira Governorate",
            "Beni Suef Governorate",
            "Cairo Governorate",
            "Dakahlia Governorate",
            "Damietta Governorate",
            "Faiyum Governorate",
            "Gharbia Governorate",
            "Giza Governorate",
            "Ismailia Governorate",
            "Kafr el-Sheikh Governorate",
            "Matruh Governorate",
            "Minya Governorate",
            "Monufia Governorate",
            "New Valley Governorate",
            "North Sinai Governorate",
            "Port Said Governorate",
            "Qalyubia Governorate",
            "Qena Governorate",
            "Red Sea Governorate",
            "Sharqia Governorate",
            "Sohag Governorate",
            "South Sinai Governorate",
            "Suez Governorate",
            "(unassigned)",
            "(unassigned)",
            "Anseba",
            "Debub",
            "Debubawi Keyih Bahri",
            "Gash-Barka",
            "Maakel",
            "Semenawi Keyih Bahri",
            "(unassigned)",
            "Addis Ababa",
            "Afar",
            "Amara",
            "Benshangul-Gumaz",
            "Dire Dawa",
            "Gambela Peoples",
            "Harari People",
            "Oromia",
            "Somali",
            "Southern Nations, Nationalities and Peoples",
            "Tigrai",
            "(unassigned)",
            "Estuaire Province",
            "Haut-OgoouÃ© Province",
            "Moyen-OgoouÃ© Province",
            "NgouniÃ© Province",
            "Nyanga Province",
            "OgoouÃ©-Ivindo Province",
            "OgoouÃ©-Lolo Province",
            "OgoouÃ©-Maritime Province",
            "Woleu-Ntem Province",
            "(unassigned)",
            "Ashanti Region",
            "Brong-Ahafo Region",
            "Central Region",
            "Eastern Region",
            "Greater Accra Region",
            "Northern Region",
            "Upper East Region",
            "Upper West Region",
            "Volta Region",
            "Western Region",
            "(unassigned)",
            "Banjul",
            "Central River",
            "Lower River",
            "MacCarthy Island",
            "North Bank",
            "Upper River",
            "Western",
            "(unassigned)",
            "Beyla",
            "Boffa",
            "Boke",
            "Conakry",
            "Coyah",
            "Dabola",
            "Dalaba",
            "Dinguiraye",
            "Dubreka",
            "Faranah",
            "Forecariah",
            "Fria",
            "Gaoual",
            "Guekedou",
            "Kankan",
            "Kerouane",
            "Kindia",
            "Kissidougou",
            "Koubia",
            "Koundara",
            "Kouroussa",
            "Labe",
            "Lelouma",
            "Lola",
            "Macenta",
            "Mali",
            "Mamou",
            "Mandiana",
            "Nzerekore",
            "Pita",
            "Siguiri",
            "Telimele",
            "Tougue",
            "Yomou",
            "(unassigned)",
            "Annobon",
            "Bioko Norte",
            "Bioko Sur",
            "Centro Sur",
            "Kie-Ntem",
            "Litoral",
            "Region Continental",
            "Region Insular",
            "Wele-Nzas",
            "(unassigned)",
            "BafatÃ¡",
            "Biombo",
            "Bissau",
            "Bolama",
            "Cacheu",
            "Gabu",
            "Oio",
            "Quloara",
            "Tombali",
            "(unassigned)",
            "Central Province",
            "Coast Province",
            "Eastern Province",
            "Nairobi Province",
            "North-Eastern Province",
            "Nyanza Province",
            "Rift Valley Province",
            "Western Province",
            "(unassigned)",
            "Anjouan Ndzouani",
            "Grande Comore Ngazidja",
            "Moheli Moili",
            "(unassigned)",
            "Bomi",
            "Bong",
            "Grand Basaa",
            "Grand Cape Mount",
            "Grand Gedeh",
            "Grand Kru",
            "Lofa",
            "Margibi",
            "Maryland",
            "Montserrado",
            "Nimba",
            "Rivercess",
            "Sinoe",
            "(unassigned)",
            "Berea",
            "Butha-Buthe",
            "Leribe",
            "Mafeteng",
            "Maseru",
            "Mohale\'s Hoek",
            "Mokhotlong",
            "Qacha\'s Nek",
            "Quthing",
            "Thaba-Tseka",
            "(unassigned)",
            "Al Butnan District",
            "Al Jabal al Akhdar District",
            "Al Jabal al Gharbi District",
            "Al Jfara District",
            "Al Jufrah District",
            "Al Kufrah District",
            "Al Marj District",
            "Al Murgub District",
            "Al Wahat District",
            "An Nuqat al Khams District",
            "Az Zawiyah District",
            "Benghazi District",
            "Darnah District",
            "Ghat District",
            "Misurata District",
            "Murzuq District",
            "Nalut District",
            "Sabha District",
            "Surt District",
            "Tripoli District",
            "Wadi Al Hayaa District",
            "Wadi Al Shatii District",
            "(unassigned)",
            "AÃ¯t Baha",
            "AÃ¯t Melloul",
            "Agadir",
            "Al Haouz",
            "Al HoceÃ¯ma",
            "Assa-Zag",
            "Azilal",
            "Ben Sllmane",
            "Beni Mellal",
            "Berkane",
            "Boujdour",
            "Boulemane",
            "Casablanca",
            "Chefchaouene",
            "Chichaoua",
            "El Hajeb",
            "El Jadida",
            "Errachidia",
            "Es Smara",
            "Essaouira",
            "FÃ¨s",
            "Figuig",
            "Guelmim",
            "Ifrane",
            "Jerada",
            "KÃ©nitra",
            "Kelaat Sraghna",
            "Khemisaet",
            "Khenifra",
            "Khouribga",
            "LaÃ¢youne (EH)",
            "Larache",
            "Marrakech",
            "MeknsÃ¨s",
            "Nador",
            "Ouarzazate",
            "Oued ed Dahab (EH)",
            "Oujda",
            "Rabat-SalÃ©",
            "Safi",
            "Sefrou",
            "Settat",
            "Sidl Kacem",
            "TÃ©touan",
            "Tanger",
            "Tan-Tan",
            "Taounate",
            "Taroudannt",
            "Tata",
            "Taza",
            "Tiznit",
            "(unassigned)",
            "Antananarivo",
            "Antsiranana",
            "Fianarantsoa",
            "Mahajanga",
            "Toamasina",
            "Toliara",
            "(unassigned)",
            "Bamako",
            "Gao",
            "Kayes",
            "Kidal",
            "Koulikoro",
            "Mopti",
            "SÃ©gou",
            "Sikasso",
            "Tombouctou",
            "(unassigned)",
            "Adrar",
            "Assaba",
            "Brakna",
            "Dakhlet Nouadhibou",
            "Gorgol",
            "Guidimaka",
            "Hodh ech Chargui",
            "Hodh el Charbi",
            "Inchiri",
            "Nouakchott",
            "Tagant",
            "Tiris Zemmour",
            "Trarza",
            "(unassigned)",
            "Agalega Islands",
            "Beau Bassin-Rose Hill",
            "Black River",
            "Cargados Carajos Shoals",
            "Curepipe",
            "Flacq",
            "Grand Port",
            "Moka",
            "Pamplemousses",
            "Plaines Wilhems",
            "Port Louis",
            "Port Louis (district)",
            "Quatre Bornes",
            "Riviere du Rempart",
            "Rodrigues Island",
            "Savanne",
            "Vacosa-Phoenix",
            "(unassigned)",
            "Balaka",
            "Blantyre",
            "Chikwawa",
            "Chiradzulu",
            "Chitipa",
            "Dedza",
            "Dowa",
            "Karonga",
            "Kasungu",
            "Likoma Island",
            "Lilongwe",
            "Machinga",
            "Mangochi",
            "Mchinji",
            "Mulanje",
            "Mwanza",
            "Mzimba",
            "Nkhata Bay",
            "Nkhotakota",
            "Nsanje",
            "Ntcheu",
            "Ntchisi",
            "Phalomba",
            "Rumphi",
            "Salima",
            "Thyolo",
            "Zomba",
            "(unassigned)",
            "Cabo Delgado Province",
            "Gaza Province",
            "Inhambane Province",
            "Manica Province",
            "Maputo (city)",
            "Maputo Province",
            "Nampula Province",
            "Niassa Province",
            "Sofala Province",
            "Tete Province",
            "Zambezia Province",
            "(unassigned)",
            "Caprivi",
            "Erongo",
            "Hardap",
            "Karas",
            "Khomae",
            "Kunene",
            "Ohangwena",
            "Okavango",
            "Omaheke",
            "Omusati",
            "Oshana",
            "Oshikoto",
            "Otjozondjupa",
            "(unassigned)",
            "Agadez Region",
            "Diffa Region",
            "Dosso Region",
            "Maradi Region",
            "Niamey Capital District",
            "Tahoua Region",
            "TillabÃ©ri Region",
            "Zinder Region",
            "(unassigned)",
            "Abia",
            "Abuja Capital Territory",
            "Adamawa",
            "Akwa Ibom",
            "Anambra",
            "Bauchi",
            "Bayelsa",
            "Benue",
            "Borno",
            "Cross River",
            "Delta",
            "Ebonyi",
            "Edo",
            "Ekiti",
            "Enugu",
            "Gombe",
            "Imo",
            "Jigawa",
            "Kaduna",
            "Kano",
            "Katsina",
            "Kebbi",
            "Kogi",
            "Kwara",
            "Lagos",
            "Nassarawa",
            "Niger",
            "Ogun",
            "Ondo",
            "Osun",
            "Oyo",
            "Plateau",
            "Rivers",
            "Sokoto",
            "Taraba",
            "Yobe",
            "Zamfara",
            "(unassigned)",
            "(unassigned)",
            "Butare",
            "Byumba",
            "Cyangugu",
            "East",
            "Gikongoro",
            "Gisenyi",
            "Gitarama",
            "Kibungo",
            "Kibuye",
            "Kigali-Rural Kigali y\' Icyaro",
            "Kigali-Ville Kigali Ngari",
            "Mutara",
            "North",
            "Ruhengeri",
            "South",
            "Ville de Kigali",
            "West",
            "(unassigned)",
            "Anse Ã‰toile",
            "Anse aux Pins",
            "Anse Boileau",
            "Anse Louis",
            "Anse Royale",
            "Baie Lazare",
            "Baie Sainte Anne",
            "Beau Vallon",
            "Bel Air",
            "Bel Ombre",
            "Cascade",
            "Glacis",
            "Grand\' Anse (MahÃ©)",
            "Grand\' Anse (Praslin)",
            "La Digue",
            "La RiviÃ¨re Anglaise",
            "Mont Buxton",
            "Mont Fleuri",
            "Plaisance",
            "Pointe La Rue",
            "Port Glaud",
            "Saint Louis",
            "Takamaka",
            "(unassigned)",
            "Al Jazirah",
            "Al Qadarif",
            "Blue Nile",
            "Central Darfur",
            "East Darfur",
            "Kassala State",
            "Khartoum State",
            "North Darfur",
            "North Kurdufan",
            "Northern",
            "Red Sea",
            "River Nile",
            "Sennar",
            "South Darfur",
            "South Kurdufan",
            "West Darfur",
            "Western Kurdufan",
            "White Nile",
            "(unassigned)",
            "Ascension",
            "Saint Helena",
            "Tristan da Cunha",
            "(unassigned)",
            "Eastern Province",
            "Northern Province",
            "Southern Province",
            "Western Area",
            "(unassigned)",
            "Dakar",
            "Diourbel",
            "Fatick",
            "Kaolack",
            "Kolda",
            "Louga",
            "Matam",
            "Saint-Louis",
            "Tambacounda",
            "Thies",
            "Ziguinchor",
            "(unassigned)",
            "Awdal",
            "Bakool",
            "Banaadir",
            "Bari",
            "Bay",
            "Galguduud",
            "Gedo",
            "Hiirsan",
            "Jubbada Dhexe",
            "Jubbada Hoose",
            "Mudug",
            "Nugaal",
            "Saneag",
            "Shabeellaha Dhexe",
            "Shabeellaha Hoose",
            "Sool",
            "Togdheer",
            "Woqooyi Galbeed",
            "(unassigned)",
            "Central Equatoria",
            "Eastern Equatoria",
            "Jonglei",
            "Lakes",
            "Northern Bahr el Ghazal",
            "Unity",
            "Upper Nile",
            "Warrap",
            "Western Bahr el Ghazal",
            "Western Equatoria",
            "(unassigned)",
            "Principe",
            "SÃ£o TomÃ©",
            "(unassigned)",
            "Hhohho",
            "Lubombo",
            "Manzini",
            "Shiselweni",
            "(unassigned)",
            "Batha",
            "Biltine",
            "Borkou-Ennedi-Tibesti",
            "Chari-Baguirmi",
            "Guera",
            "Kanem",
            "Lac",
            "Logone-Occidental",
            "Logone-Oriental",
            "Mayo-Kebbi",
            "Moyen-Chari",
            "Ouaddai",
            "Salamat",
            "Tandjile",
            "(unassigned)",
            "Centrale Region",
            "Kara Region",
            "Maritime Region",
            "Plateaux Region",
            "Savanes Region",
            "(unassigned)",
            "Ariana Governorate",
            "BÃ©ja Governorate",
            "Ben Arous Governorate",
            "Bizerte Governorate",
            "GabÃ¨s Governorate",
            "Gafsa Governorate",
            "Jendouba Governorate",
            "Kairouan Governorate",
            "Kasserine Governorate",
            "Kebili Governorate",
            "Kef Governorate",
            "Mahdia Governorate",
            "Manouba Governorate",
            "Medenine Governorate",
            "Monastir Governorate",
            "Nabeul Governorate",
            "Sfax Governorate",
            "Sidi Bou Zid Governorate",
            "Siliana Governorate",
            "Sousse Governorate",
            "Tataouine Governorate",
            "Tozeur Governorate",
            "Tunis Governorate",
            "Zaghouan Governorate",
            "(unassigned)",
            "Arusha",
            "Dar-es-Salaam",
            "Dodoma",
            "Iringa",
            "Kagera",
            "Kaskazini Pemba",
            "Kaskazini Unguja",
            "Kilimanjaro",
            "Kusini Unguja",
            "Lindi",
            "Manyara",
            "Mara",
            "Mbeya",
            "Mjini Magharibi",
            "Morogoro",
            "Mtwara",
            "Mwanza",
            "Pwani",
            "Rukwa",
            "Rusini Pemba",
            "Ruvuma",
            "Shinyanga",
            "Singida",
            "Tabora",
            "Tanga",
            "Xigoma",
            "(unassigned)",
            "Adjumani District",
            "Apac District",
            "Arua District",
            "Bugiri District",
            "Bundibugyo District",
            "Bushenyi District",
            "Busia District",
            "Gulu District",
            "Hoima District",
            "Iganga District",
            "Jinja District",
            "Kabale District",
            "Kabarole District",
            "Kaberamaido District",
            "Kalangala District",
            "Kampala District",
            "Kamuli District",
            "Kamwenge District",
            "Kanungu District",
            "Kapchorwa District",
            "Kasese District",
            "Katakwi District",
            "Kayunga District",
            "Kibaale District",
            "Kiboga District",
            "Kisoro District",
            "Kitgum District",
            "Kotido District",
            "Kumi District",
            "Kyenjojo District",
            "Lira District",
            "Luwero District",
            "Masaka District",
            "Masindi District",
            "Mayuge District",
            "Mbale District",
            "Mbarara District",
            "Moroto District",
            "Moyo District",
            "Mpigi District",
            "Mubende District",
            "Mukono District",
            "Nakapiripirit District",
            "Nakasongola District",
            "Nebbi District",
            "Ntungamo District",
            "Pader District",
            "Pallisa District",
            "Rakai District",
            "Rukungiri District",
            "Sembabule District",
            "Sironko District",
            "Soroti District",
            "Tororo District",
            "Wakiso District",
            "Yumbe District",
            "(unassigned)",
            "(unassigned)",
            "Eastern Cape",
            "Free State",
            "Gauteng",
            "Kwazulu-Natal",
            "Limpopo",
            "Mpumalanga",
            "Northern Cape",
            "North-West",
            "Western Cape",
            "(unassigned)",
            "Central Province",
            "Copperbelt Province",
            "Eastern Province",
            "Luapula Province",
            "Lusaka Province",
            "Northern Province",
            "North-Western Province",
            "Southern Province",
            "Western Province",
            "(unassigned)",
            "Bulawayo",
            "Harare",
            "Manicaland",
            "Mashonaland Central",
            "Mashonaland East",
            "Mashonaland West",
            "Masvingo",
            "Matabeleland North",
            "Matabeleland South",
            "Midlands",
            "(unassigned)",
            "(unassigned)",
            "(unassigned)",
            "(unassigned)",
            "(unassigned)",
            "Abu Dhabi Emirate",
            "Ajman Emirate",
            "Dubai Emirate",
            "Fujairah Emirate",
            "Ras al-Khaimah Emirate",
            "Sharjah Emirate",
            "Umm al-Quwain Emirate",
            "(unassigned)",
            "Badakhshan Province",
            "Badghis Province",
            "Baghlan Province",
            "Balkh Province",
            "Bamiyan Province",
            "Daykundi Province",
            "Farah Province",
            "Faryab Province",
            "GhÅr Province",
            "Ghazni Province",
            "Helmand Province",
            "Herat Province",
            "Jowzjan Province",
            "Kabul Province",
            "Kandahar Province",
            "Kapisa Province",
            "Khost Province",
            "Kunar Province",
            "Kunduz Province",
            "Laghman Province",
            "Logar Province",
            "Nangarhar Province",
            "Nimruz Province",
            "Nurestan Province",
            "OrÅ«zgÄn Province",
            "Paktia Province",
            "Paktika Province",
            "Panjshir Province",
            "Parwan Province",
            "Samangan Province",
            "Sar-e Pol Province",
            "Takhar Province",
            "Wardak Province",
            "Zabul Province",
            "(unassigned)",
            "Aragatsotn Province",
            "Ararat Province",
            "Armavir Province",
            "Gegharkunik Province",
            "Kotayk Province",
            "Lori Province",
            "Shirak Province",
            "Syunik Province",
            "Tavush Province",
            "Vayots Dzor Province",
            "Yerevan (capital district)",
            "(unassigned)",
            "Abseron",
            "Agcabadi",
            "Agdam",
            "Agdas",
            "Agstafa",
            "Agsu",
            "Ali Bayramli",
            "Astara",
            "Babak",
            "Baki",
            "Balakan",
            "Barda",
            "Beylagan",
            "Bilasuvar",
            "Cabrayll",
            "Calilabad",
            "Culfa",
            "Daskasan",
            "Davaci",
            "Fuzuli",
            "Gadabay",
            "Ganca",
            "Goranboy",
            "Goycay",
            "Haciqabul",
            "Imisli",
            "Ismayilli",
            "Kalbacar",
            "Kurdamir",
            "Lacin",
            "Lankaran",
            "Lerik",
            "Masalli",
            "Mingacevir",
            "Naftalan",
            "Naxcivan",
            "Neftcala",
            "Oguz",
            "Ordubad",
            "Qabala",
            "Qax",
            "Qazax",
            "Qobustan",
            "Quba",
            "Qubadli",
            "Qusar",
            "Saatli",
            "Sabirabad",
            "Sadarak",
            "Sahbuz",
            "Saki",
            "Salyan",
            "Samaxi",
            "Samkir",
            "Samux",
            "Sarur",
            "Siyazan",
            "Sumqayit",
            "Susa",
            "Tartar",
            "Tovuz",
            "Ucar",
            "Xacmaz",
            "Xankandi",
            "Xanlar",
            "Xizi",
            "Xocali",
            "Xocavand",
            "Yardimli",
            "Yevlax",
            "Zangilan",
            "Zaqatala",
            "Zardab",
            "(unassigned)",
            "Barisal Division",
            "Chittagong Division",
            "Dhaka Division",
            "Khulna Division",
            "Rajshahi Division",
            "Sylhet Division",
            "(unassigned)",
            "Capital Governorate",
            "Central Governorate",
            "Muharraq Governorate",
            "Northern Governorate",
            "Southern Governorate",
            "(unassigned)",
            "Belait",
            "Brunei-Muara",
            "Temburong",
            "Tutong",
            "(unassigned)",
            "Bumthang",
            "Chhukha",
            "Dagana",
            "Gasa",
            "Ha",
            "Lhuentse",
            "Monggar",
            "Paro",
            "Pemagatshel",
            "Punakha",
            "Samdrup Jongkha",
            "Samtee",
            "Sarpang",
            "Thimphu",
            "Trashi Yangtse",
            "Trashigang",
            "Trongsa",
            "Tsirang",
            "Wangdue Phodrang",
            "Zhemgang",
            "(unassigned)",
            "(unassigned)",
            "Anhui Province",
            "Beijing Municipality",
            "Chongqing Municipality",
            "Fujian Province",
            "Gansu Province",
            "Guangdong Province",
            "Guangxi Autonomous Region",
            "Guizhou Province",
            "Hainan Province",
            "Hebei Province",
            "Heilongjiang Province",
            "Henan Province",
            "Hong Kong Special Administrative Region",
            "Hubei Province",
            "Hunan Province",
            "Inner Mongolia Autonomous Region",
            "Jiangsu Province",
            "Jiangxi Province",
            "Jilin Province",
            "Liaoning Province",
            "Macau Special Administrative Region",
            "Ningxia Autonomous Region",
            "Qinghai Province",
            "Shaanxi Province",
            "Shandong Province",
            "Shanghai Municipality",
            "Shanxi Province",
            "Sichuan Province",
            "Taiwan (disputed)",
            "Tianjin Municipality",
            "Tibet Autonomous Region",
            "Xinjiang Autonomous Region",
            "Yunnan Province",
            "Zhejiang Province",
            "(unassigned)",
            "(unassigned)",
            "Famagusta District",
            "Kyrenia District",
            "Larnarca District",
            "Limassol District",
            "Nicosia District",
            "Paphos District",
            "(unassigned)",
            "Abkhazia",
            "Adjara",
            "Guria",
            "Imereti",
            "Kakheti",
            "Kvemo Kartli",
            "Mtskheta-Mtianeti",
            "Racha-Lechkhumi and Kvemo Svaneti",
            "Samegrelo-Zemo Svaneti",
            "Samtskhe-Javakheti",
            "Shida Kartli",
            "Tbilisi",
            "(unassigned)",
            "(unassigned)",
            "Aceh",
            "Bali",
            "Bangka Belitung",
            "Banten",
            "Bengkulu",
            "East Kalimantan",
            "Gorontalo",
            "Irian Jaya",
            "Jakarta Raya",
            "Jambi",
            "Jawa Barat",
            "Jawa Tengah",
            "Jawa Timur",
            "Kalimantan Barat",
            "Kalimantan Selatan",
            "Kalimantan Timur",
            "Kepulauan Riau",
            "Lampung",
            "Maluku",
            "Maluku Utara",
            "Nusa Tenggara Barat",
            "Nusa Tenggara Timur",
            "Papua",
            "Riau",
            "Sulawesi Selatan",
            "Sulawesi Tengah",
            "Sulawesi Tenggara",
            "Sulawesi Utara",
            "Sumatera Utara",
            "Sumatra Barat",
            "Sumatra Selatan",
            "Yogyakarta",
            "(unassigned)",
            "Center District",
            "Haifa District",
            "Jerusalem District",
            "North District",
            "South District",
            "Tel Aviv District",
            "(unassigned)",
            "Andaman and Nicobar Islands",
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chandigarh",
            "Chhattisgarh",
            "Dadra and Nagar Haveli",
            "Daman and Diu",
            "Delhi",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jammu and Kashmir",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Lakshadweep",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Orissa",
            "Pondicherry",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Tripura",
            "Uttar Pradesh",
            "Uttaranchal",
            "West Bengal",
            "(unassigned)",
            "(unassigned)",
            "Al-Anbar Governorate",
            "Al-Muthanna Governorate",
            "Al-Qadisiyyah Governorate",
            "Arbil Governorate",
            "As-Sulaymaniyyah Governorate",
            "Babil Governorate",
            "Baghdad Governorate",
            "Basra Governorate",
            "Dhi Qar Governorate",
            "Diyala Governorate",
            "Duhok Governorate",
            "Karbala Governorate",
            "Kirkuk Governorate",
            "Maysan Governorate",
            "Najaf Governorate",
            "Ninawa Governorate",
            "Salah ad Din Governorate",
            "Wasit Governorate",
            "(unassigned)",
            "Ardabil Province",
            "Bushehr Province",
            "Chaharmahal and Bakhtiari Province",
            "East Azarbaijan Province",
            "Esfahan Province",
            "Fars Province",
            "Gilan Province",
            "Golestan Province",
            "Hamadan Province",
            "Hormozgan Province",
            "Iiam Province",
            "Kerman Province",
            "Kermanshah Province",
            "Khuzestan Province",
            "Kohgiluyeh and Boyer-Ahmad Province",
            "Kordestan Province",
            "Lorestan Province",
            "Markazi Province",
            "Mazandaran Province",
            "North Khorasan Province",
            "Qazvin Province",
            "Qom Province",
            "Razavi Khorasan Province",
            "Semnan Province",
            "Sistan and Baluchestan Province",
            "South Khorasan Province",
            "Tehran Province",
            "West Azarbaijan Province",
            "Yazd Province",
            "Zanjan Province",
            "(unassigned)",
            "Ajln",
            "Al \'Aqaba",
            "Al Balqa\'",
            "Al Karak",
            "Al Mafraq",
            "Amman",
            "At Tafilah",
            "Az Zarga",
            "Irbid",
            "Jarash",
            "Ma\'an",
            "Madaba",
            "(unassigned)",
            "Aichi Prefecture",
            "Akita Prefecture",
            "ÅŒita Prefecture",
            "ÅŒsaka Prefecture",
            "Aomori Prefecture",
            "Chiba Prefecture",
            "Ehime Prefecture",
            "Fukui Prefecture",
            "Fukuoka Prefecture",
            "Fukusima Prefecture",
            "Gifu Prefecture",
            "Gunma Prefecture",
            "Hiroshima Prefecture",
            "HokkaidÅ Prefecture",
            "HyÅgo Prefecture",
            "Ibaraki Prefecture",
            "Ishikawa Prefecture",
            "Iwate Prefecture",
            "KÅchi Prefecture",
            "Kagawa Prefecture",
            "Kagoshima Prefecture",
            "Kanagawa Prefecture",
            "Kumamoto Prefecture",
            "KyÅto Prefecture",
            "Mie Prefecture",
            "Miyagi Prefecture",
            "Miyazaki Prefecture",
            "Nagano Prefecture",
            "Nagasaki Prefecture",
            "Nara Prefecture",
            "Niigata Prefecture",
            "Okayama Prefecture",
            "Okinawa Prefecture",
            "Saga Prefecture",
            "Saitama Prefecture",
            "Shiga Prefecture",
            "Shimane Prefecture",
            "Shizuoka Prefecture",
            "TÅkyÅ Prefecture",
            "Tochigi Prefecture",
            "Tokushima Prefecture",
            "Tottori Prefecture",
            "Toyama Prefecture",
            "Wakayama Prefecture",
            "Yamagata Prefecture",
            "Yamaguchi Prefecture",
            "Yamanashi Prefecture",
            "(unassigned)",
            "Batken",
            "Bishkek",
            "Chuy",
            "Issyk-Kul",
            "Jalal-Abad",
            "Naryn",
            "Osh",
            "Talas",
            "(unassigned)",
            "Baat Dambang",
            "Banteay Mean Chey",
            "Kach Kong",
            "Kampong Chaam",
            "Kampong Chhnang",
            "Kampong Spueu",
            "Kampong Thum",
            "Kampot",
            "Kandaal",
            "Krachoh",
            "Krong Kaeb",
            "Krong Pailin",
            "Mondol Kiri",
            "Otdar Mean Chey",
            "Phnom Penh",
            "Pousaat",
            "Preah Vihear",
            "Prey Veaeng",
            "Rotanak Kiri",
            "Siem Reab",
            "Stueng Traeng",
            "Svaay Rieng",
            "Taakaev",
            "Xrong Preah Sihanouk",
            "(unassigned)",
            "Chagang-do",
            "Hamgyongbuk-do",
            "Hamgyongnam-do",
            "Hwanghaebuk-do",
            "Hwanghaenam-do",
            "Kaesong-si",
            "Kangwon-do",
            "Najin Sonbong-si",
            "Nampo-si",
            "Pyonganbuk-do",
            "Pyongannam-do",
            "Pyongyang-ai",
            "Yanggang-do",
            "(unassigned)",
            "Busan Gwang\'yeogsi",
            "Chungcheongbugdo",
            "Chungcheongnamdo",
            "Daegu Gwang\'yeogsi",
            "Daejeon Gwang\'yeogsi",
            "Gang\'weondo",
            "Gwangju Gwang\'yeogsi",
            "Gyeonggido",
            "Gyeongsangbugdo",
            "Gyeongsangnamdo",
            "Incheon Gwang\'yeogsi",
            "Jejudo",
            "Jeonrabugdo",
            "Jeonranamdo",
            "Seoul Teugbyeolsi",
            "Ulsan Gwang\'yeogsi",
            "(unassigned)",
            "Al Ahmadi Governorate",
            "Al Asimah Governorate",
            "Al Farwaniyah Governorate",
            "Al Jahra Governorate",
            "Hawalli Governorate",
            "Mubarak Al-Kabeer Governorate",
            "(unassigned)",
            "Akmola",
            "Aktobe",
            "Almaty",
            "Almaty (city)",
            "Astana",
            "Atyrau",
            "Baikonur",
            "East Kazakhstan",
            "Karagandy",
            "Kostanay",
            "Kyzylorda",
            "Mangystau",
            "North Kazakhstan",
            "Pavlodar",
            "South Kazakhstan",
            "West Kazakhstan",
            "Zhambyl",
            "(unassigned)",
            "Attapu",
            "Bokeo",
            "Bolikhamxai",
            "Champasak",
            "Houaphan",
            "Khammouan",
            "Louang Namtha",
            "Louangphabang",
            "Oudomxai",
            "Phongsali",
            "Salavan",
            "Savannakhet",
            "Vientiane",
            "Xaignabouli",
            "Xekong",
            "Xiangkhoang",
            "Xiasomboun",
            "(unassigned)",
            "Aakkar Governorate",
            "Baalbek-Hermel Governorate",
            "Beirut Governorate",
            "Beqaa Governorate",
            "Mount Lebanon Governorate",
            "Nabatieh Governorate",
            "North Governorate",
            "South Governorate",
            "(unassigned)",
            "Central Province",
            "Eastern Province",
            "North Central Province",
            "North Western Province",
            "Northern Province",
            "Sabaragamuwa Province",
            "Southern Province",
            "Uva Province",
            "Western Province",
            "(unassigned)",
            "Ayeyarwady Division",
            "Bago Division",
            "Chin State",
            "Kachin State",
            "Kayah State",
            "Kayin State",
            "Magway Division",
            "Mandalay Division",
            "Mon State",
            "Rakhine State",
            "Sagaing Division",
            "Shan State",
            "Tanintharyi Division",
            "Yangon Division",
            "(unassigned)",
            "Ã–mnÃ¶govi",
            "Arhangay",
            "Ã–vÃ¶rkhangai",
            "Bayanhongor",
            "Bayan-Olgiy",
            "Bulgan",
            "Darhan uul",
            "Dornod",
            "Dornogov,",
            "DundgovL",
            "Dzavhan",
            "Govi-Altay",
            "Govi-Smber",
            "Hentiy",
            "KhÃ¶vsgÃ¶l",
            "Khovd",
            "Orhon",
            "Selenge",
            "Shbaatar",
            "Tov",
            "Ulanbaatar",
            "Uvs",
            "(unassigned)",
            "(unassigned)",
            "Alif Alif Atoll",
            "Baa",
            "Dhaalu",
            "Faafu",
            "Gaaf Alif",
            "Gaafu Dhaalu Atoll",
            "Gnaviyani",
            "Haa Alif",
            "Haa Dhaalu Atoll",
            "Kaafu",
            "Laamu Atoll",
            "Lhaviyani",
            "MalÃ© Capital",
            "Meemu",
            "Noonu",
            "Raa",
            "Seenu Atoll",
            "Shaviyani",
            "Thaa",
            "Vaavu",
            "(unassigned)",
            "Johor",
            "Kedah",
            "Kelantan",
            "Melaka",
            "Negeri Sembilan",
            "Pahang",
            "Perak",
            "Perlis",
            "Pulau Pinang",
            "Sabah",
            "Sarawak",
            "Selangor",
            "Terengganu",
            "Wilayah Persekutuan Kuala Lumpur",
            "Wilayah Persekutuan Labuan",
            "Wilayah Persekutuan Putrajaya",
            "(unassigned)",
            "Bagmati",
            "Bheri",
            "Dhawalagiri",
            "Gandaki",
            "Janakpur",
            "Karnali",
            "Kosi",
            "Lumbini",
            "Mahakali",
            "Mechi",
            "Narayani",
            "Rapti",
            "Sagarmatha",
            "Seti",
            "(unassigned)",
            "Ad Dakhillyah",
            "Al Batinah",
            "Al Janblyah",
            "Al Wusta",
            "Ash Sharqlyah",
            "Az Zahirah",
            "Masqat",
            "Musandam",
            "(unassigned)",
            "Abra",
            "Agusan del Norte",
            "Agusan del Sur",
            "Aklan",
            "Albay",
            "Antique",
            "Apayao",
            "Aurora",
            "Basilan",
            "Batanes",
            "Batangas",
            "Batasn",
            "Benguet",
            "Biliran",
            "Bohol",
            "Bukidnon",
            "Bulacan",
            "Cagayan",
            "Camarines Norte",
            "Camarines Sur",
            "Camiguin",
            "Capiz",
            "Catanduanes",
            "Cavite",
            "Cebu",
            "Compostela Valley",
            "Davao",
            "Davao del Sur",
            "Davao Oriental",
            "Eastern Samar",
            "Guimaras",
            "Ifugao",
            "Ilocos Norte",
            "Ilocos Sur",
            "Iloilo",
            "Isabela",
            "Kalinga-Apayso",
            "La Union",
            "Laguna",
            "Lanao del Norte",
            "Lanao del Sur",
            "Leyte",
            "Maguindanao",
            "Marinduque",
            "Masbate",
            "Mindoro Occidental",
            "Mindoro Oriental",
            "Misamis Occidental",
            "Misamis Oriental",
            "Mountain Province",
            "Negroe Occidental",
            "Negros Oriental",
            "North Cotabato",
            "Northern Samar",
            "Nueva Ecija",
            "Nueva Vizcaya",
            "Palawan",
            "Pampanga",
            "Pangasinan",
            "Quezon",
            "Quirino",
            "Rizal",
            "Romblon",
            "Sarangani",
            "Siquijor",
            "Sorsogon",
            "South Cotabato",
            "Southern Leyte",
            "Sultan Kudarat",
            "Sulu",
            "Surigao del Norte",
            "Surigao del Sur",
            "Tarlac",
            "Tawi-Tawi",
            "Western Samar",
            "Zambales",
            "Zamboanga del Norte",
            "Zamboanga del Sur",
            "Zamboanga Sibiguey",
            "(unassigned)",
            "Azad Kashmir",
            "Balochistan",
            "Federally Administered Tribal Areas",
            "Islamabad Capital Territory",
            "Northern Areas",
            "North-West Frontier",
            "Punjab",
            "Sindh",
            "(unassigned)",
            "(unassigned)",
            "Ad Dawhah Municipality",
            "Al Ghuwayriyah Municipality",
            "Al Jumayliyah Municipality",
            "Al Khawr Municipality",
            "Al Wakrah Municipality",
            "Ar Rayyan Municipality",
            "Jariyan al Batnah Municipality",
            "Madinat ash Shamal Municipality",
            "Umm Salal Municipality",
            "(unassigned)",
            "Al Batah",
            "Al Jawf",
            "Al Madinah",
            "Al Qasim",
            "Ash Sharqiyah",
            "Asir",
            "Ha\'il",
            "Jlzan",
            "Makkah",
            "Najran",
            "Riyadh",
            "Tabuk",
            "The Northern Border",
            "(unassigned)",
            "Central Singapore",
            "North East",
            "North West",
            "South East",
            "South West",
            "(unassigned)",
            "Aleppo Governorate",
            "Al-Hasakah Governorate",
            "Ar-Raqqah Governorate",
            "As-Suwayda Governorate",
            "Damascus Governorate",
            "Daraa Governorate",
            "Deir ez-Zor Governorate",
            "Hama Governorate",
            "Homs Governorate",
            "Idlib Governorate",
            "Latakia Governorate",
            "Quneitra Governorate",
            "Rif Dimashq Governorate",
            "Tartus Governorate",
            "(unassigned)",
            "Amnat Charoen Province",
            "Ang Thong Province",
            "Bangkok Province",
            "Buri Ram Province",
            "Chachoengsao Province",
            "Chai Nat Province",
            "Chaiyaphum Province",
            "Chanthaburi Province",
            "Chiang Mai Province",
            "Chiang Rai Province",
            "Chon Buri Province",
            "Chumphon Province",
            "Kalasin Province",
            "Kamphaeng Phet Province",
            "Kanchanaburi Province",
            "Khon Kaen Province",
            "Krabi Province",
            "Lampang Province",
            "Lamphun Province",
            "Loei Province",
            "Lop Buri Province",
            "Mae Hong Son Province",
            "Maha Sarakham Province",
            "Mukdahan Province",
            "Nakhon Nayok Province",
            "Nakhon Pathom Province",
            "Nakhon Phanom Province",
            "Nakhon Ratchasima Province",
            "Nakhon Sawan Province",
            "Nakhon Si Thammarat Province",
            "Nan Province",
            "Narathiwat Province",
            "Nong Bua Lam Phu Province",
            "Nong Khai Province",
            "Nonthaburi Province",
            "Pathum Thani Province",
            "Pattani Province",
            "Pattaya Province",
            "Phang Nga Province",
            "Phattalung Province",
            "Phayao Province",
            "Phetchabun Province",
            "Phetchaburi Province",
            "Phichit Province",
            "Phitsanulok Province",
            "Phra Nakhon Si Ayutthaya Province",
            "Phrae Province",
            "Phuket Province",
            "Prachin Buri Province",
            "Prachuap Khiri Khan Province",
            "Ranong Province",
            "Ratchaburi Province",
            "Rayong Province",
            "Roi Et Province",
            "Sa Kaeo Province",
            "Sakon Nakhon Province",
            "Samut Prakan Province",
            "Samut Sakhon Province",
            "Samut Songkhram Province",
            "Saraburi Province",
            "Satun Province",
            "Si Sa Ket Province",
            "Sing Buri Province",
            "Songkhla Province",
            "Sukhothai Province",
            "Suphan Buri Province",
            "Surat Thani Province",
            "Surin Province",
            "Tak Province",
            "Trang Province",
            "Trat Province",
            "Ubon Ratchathani Province",
            "Udon Thani Province",
            "Uthai Thani Province",
            "Uttaradit Province",
            "Yala Province",
            "Yasothon Province",
            "(unassigned)",
            "Gorno-Badakhshan Autonomous Province",
            "Khatlon Province",
            "Region of Republican Subordination",
            "Sughd Province",
            "(unassigned)",
            "Aileu",
            "Ainaro",
            "Baucau",
            "Bobonaro",
            "Cova Lima",
            "Dili",
            "Ermera",
            "LautÃ©m",
            "Liquica",
            "Manafahi",
            "Manatuto",
            "Oecussi",
            "Viqueque",
            "(unassigned)",
            "Ahal",
            "Balkan",
            "DaÅŸoguz",
            "Lebap",
            "Mary",
            "(unassigned)",
            "Ä°stanbul",
            "Ä°zmir",
            "Ã‡anakkale",
            "Ã‡ankÄ±rÄ±",
            "Ã‡orum",
            "AÄŸrÄ±",
            "AdÄ±yaman",
            "Adana",
            "Afyonkarahisar",
            "Aksaray",
            "Amasya",
            "Ankara",
            "Antalya",
            "Ardahan",
            "Artvin",
            "Aydin",
            "ÅžÄ±rnak",
            "ÅžanlÄ±urfa",
            "BalÄ±kesir",
            "Bartin",
            "Batman",
            "Bayburt",
            "Bilecik",
            "BingÃ¶l",
            "Bitlis",
            "Bolu",
            "Burdur",
            "Bursa",
            "DÃ¼zce",
            "Denizli",
            "Diyarbakir",
            "Edirne",
            "ElazÄ±ÄŸ",
            "Erzincan",
            "Erzurum",
            "EskiÅŸehir",
            "GÃ¼mÃ¼ÅŸhane",
            "Gaziantep",
            "Giresun",
            "HakkÃ¢ri",
            "Hatay",
            "IÄŸdÄ±r",
            "Icel",
            "Isparta",
            "KÄ±rÅŸehir",
            "KÃ¼tahya",
            "KahramanmaraÅŸ",
            "KarabÃ¼k",
            "Karaman",
            "Kars",
            "Kastamonu",
            "Kayseri",
            "Kilis",
            "Kirikkale",
            "Kirklareli",
            "Kocaeli",
            "Konya",
            "Malatya",
            "Manisa",
            "Mardin",
            "MuÅŸ",
            "MuÄŸla",
            "NevÅŸehir",
            "NiÄŸde",
            "Ordu",
            "Osmaniye",
            "Rize",
            "Sakarya",
            "Samsun",
            "Siirt",
            "Sinop",
            "Sivas",
            "TekirdaÄŸ",
            "Tokat",
            "Trabzon",
            "Tunceli",
            "UÅŸak",
            "Van",
            "Yalova",
            "Yozgat",
            "Zonguldak",
            "(unassigned)",
            "Changhua County",
            "Chiayi (city)",
            "Chiayi County",
            "Hsinchu (city)",
            "Hsinchu County",
            "Hualien County",
            "Ilan County",
            "Kaohsiung (municipality)",
            "Kaohsiung County",
            "Keelung (city)",
            "Kinmen County",
            "Lienchiang County",
            "Miaoli County",
            "Nantou County",
            "Penghu County",
            "Pingtung County",
            "Taichung (city)",
            "Taichung County",
            "Tainan City",
            "Tainan County",
            "Taipei (municipality)",
            "Taipei County",
            "Taitung County",
            "Taoyuan County",
            "Yunlin County",
            "(unassigned)",
            "Andijon",
            "Buxoro",
            "Farg\'ona",
            "Jizzax",
            "Khorazm",
            "Namangan",
            "Navoiy",
            "Qashqadaryo",
            "Qoraqalpogiston Respublikasi",
            "Samarqand",
            "Sirdaryo",
            "Surxondaryo",
            "Toshkent",
            "Toshkent",
            "Xorazm",
            "(unassigned)",
            "An Giang",
            "Ba Ria - Vung Tau",
            "Bac Can",
            "Bac Giang",
            "Bac Lieu",
            "Bac Ninh",
            "Ben Tre",
            "Binh Dinh",
            "Binh Duong",
            "Binh Phuoc",
            "Binh Thuan",
            "Ca Mau",
            "Can Tho",
            "Cao Bang",
            "Da Nang, thanh pho",
            "Dac Lac",
            "Dong Nai",
            "Dong Thap",
            "Gia Lai",
            "Ha Giang",
            "Ha Nam",
            "Ha Noi, thu do",
            "Ha Tay",
            "Ha Tinh",
            "Hai Duong",
            "Hai Phong, thanh pho",
            "Ho Chi Minh, thanh pho",
            "Hoa Binh",
            "Hung Yen",
            "Khanh Hoa",
            "Kien Giang",
            "Kon Tum",
            "Lai Chau",
            "Lam Dong",
            "Lang Son",
            "Lao Cai",
            "Long An",
            "Nam Dinh",
            "Nghe An",
            "Ninh Binh",
            "Ninh Thuan",
            "Phu Tho",
            "Phu Yen",
            "Quang Binh",
            "Quang Nam",
            "Quang Ngai",
            "Quang Ninh",
            "Quang Tri",
            "Soc Trang",
            "Son La",
            "Tay Ninh",
            "Thai Binh",
            "Thai Nguyen",
            "Thanh Hoa",
            "Thua Thien-Hue",
            "Tien Giang",
            "Tra Vinh",
            "Tuyen Quang",
            "Vinh Long",
            "Vinh Phuc",
            "Yen Bai",
            "(unassigned)",
            "Abyan Governorate",
            "Ad Dali Governorate",
            "Adan Governorate",
            "Al Bayda\' Governorate",
            "Al Hudaydah Governorate",
            "Al Hydaydah Governorate",
            "Al Jawf Governorate",
            "Al Mahrah Governorate",
            "Al Mahwit Governorate",
            "Amran Governorate",
            "Dhamar Governorate",
            "Hadramawt Governorate",
            "Hajjah Governorate",
            "Ibb Governorate",
            "Lahij Governorate",
            "Ma\'rib Governorate",
            "Sa\'dah Governorate",
            "San\'a\' Governorate",
            "Shabwah Governorate",
            "Ta\'izz Governorate",
            "(unassigned)",
            "Andorra la Vella",
            "Canillo",
            "Encamp",
            "Escaldes-Engordany",
            "La Massana",
            "Ordino",
            "Sant JuliÃ  de LÃ²ria",
            "(unassigned)",
            "Berat",
            "BulqizÃ«",
            "DelvinÃ«",
            "Devoll",
            "DibÃ«r",
            "DurrÃ«s",
            "Elbasan",
            "Fier",
            "GjirokastÃ«r",
            "Gramsh",
            "Has",
            "KavajÃ«",
            "KolonjÃ«",
            "KorÃ§Ã«",
            "KrujÃ«",
            "KuÃ§ovÃ«",
            "KukÃ«s",
            "Kurbin",
            "LezhÃ«",
            "Librazhd",
            "LushnjÃ«",
            "MalÃ«si e Madhe",
            "MallakastÃ«r",
            "Mat",
            "MirditÃ«",
            "PÃ«rmet",
            "Peqin",
            "Pogradec",
            "PukÃ«",
            "SarandÃ«",
            "ShkodÃ«r",
            "Skrapar",
            "TepelenÃ«",
            "TiranÃ«",
            "TropojÃ«",
            "VlorÃ«",
            "(unassigned)",
            "Burgenland",
            "Carinthia",
            "Lower Austria",
            "Salzburg",
            "Styria",
            "Tyrol",
            "Upper Austria",
            "Vienna",
            "Vorarlberg",
            "(unassigned)",
            "Federacija Bosna i Hercegovina",
            "Republika Srpska",
            "(unassigned)",
            "Antwerp",
            "Brussels-Capital Region",
            "East Flanders",
            "Flemish Brabant",
            "Hainaut",
            "LiÃ¨ge",
            "Limburg",
            "Luxembourg",
            "Namur",
            "Walloon Brabant",
            "West Flanders",
            "(unassigned)",
            "Blagoevgrad",
            "Burgas",
            "Dobric",
            "Gabrovo",
            "Haskovo",
            "Jambol",
            "Kardzali",
            "Kyustendil",
            "Lovec",
            "Montana",
            "Pazardzik",
            "Pernik",
            "Pleven",
            "Plovdiv",
            "Razgrad",
            "Ruse",
            "Silistra",
            "Sliven",
            "Smoljan",
            "Sofia",
            "Stara Zagora",
            "Sumen",
            "Targovishte",
            "Varna",
            "Veliko Tarnovo",
            "Vidin",
            "Vraca",
            "(unassigned)",
            "Brest Voblast",
            "Homiel Voblast",
            "Hrodna Voblast",
            "Mahilyow Voblast",
            "Minsk Voblast",
            "Vitsebsk Voblast",
            "(unassigned)",
            "Aargau",
            "Appenzell Ausserrhoden",
            "Appenzell Innerrhoden",
            "Basel-City",
            "Basel-Country",
            "Berne",
            "Fribourg",
            "Geneva",
            "Glarus",
            "Grisons",
            "Jura",
            "Lucerne",
            "NeuchÃ¢tel",
            "Nidwalden",
            "Obwalden",
            "Schaffhausen",
            "Schwyz",
            "Solothurn",
            "St. Gallen",
            "Thurgau",
            "Ticino",
            "Uri",
            "Valais",
            "Vaud",
            "Zug",
            "Zurich",
            "(unassigned)",
            "ÃšstÃ­ nad Labem Region",
            "Carlsbad Region",
            "Central Bohemian Region",
            "Hradec KrÃ¡lovÃ© Region",
            "Liberec Region",
            "Moravian-Silesian Region",
            "Olomouc Region",
            "Pardubice Region",
            "PlzeÅˆ Region",
            "Prague (capital city)",
            "South Bohemian Region",
            "South Moravian Region",
            "VysoÄina Region",
            "Zlin Region",
            "(unassigned)",
            "Baden-WÃ¼rttemberg",
            "Bavaria",
            "Berlin",
            "Brandenburg",
            "Bremen",
            "Hamburg",
            "Hesse",
            "Lower Saxony",
            "Mecklenburg-Vorpommern",
            "North Rhine-Westphalia",
            "Rhineland-Palatinate",
            "Saarland",
            "Saxony",
            "Saxony-Anhalt",
            "Schleswig-Holstein",
            "Thuringia",
            "(unassigned)",
            "Capital Region",
            "Central Jutland",
            "North Jutland",
            "South Denmark",
            "Zealand",
            "(unassigned)",
            "Harju County",
            "Hiiu County",
            "Ida-Viru County",
            "JÃ¤rva County",
            "JÃµgeva County",
            "LÃ¤Ã¤ne County",
            "LÃ¤Ã¤ne-Viru County",
            "PÃ¤rnu County",
            "PÃµlva County",
            "Rapla County",
            "Saare County",
            "Tartu County",
            "VÃµru County",
            "Valga County",
            "Viljandi County",
            "(unassigned)",
            "Ãlava",
            "Ãvila",
            "Albacete",
            "Alicante",
            "AlmerÃ­a",
            "AndalucÃ­a",
            "AragÃ³n",
            "Asturias",
            "Badajoz",
            "Baleares",
            "Baleares",
            "Barcelona",
            "Basque Country",
            "Burgos",
            "CÃ¡ceres",
            "CÃ¡diz",
            "Canary Islands",
            "Cantabria",
            "CastellÃ³n",
            "Castilla y LeÃ³n",
            "Castilla-La Mancha",
            "Catalonia",
            "Ceuta",
            "Ciudad Real",
            "Cuenca",
            "Extremadura",
            "Galicia",
            "Girona",
            "Granada",
            "Guadalajara",
            "GuipÃºzcoa",
            "Huelva",
            "Huesca",
            "JaÃ©n",
            "La CoruÃ±a",
            "La Rioja",
            "Las Palmas",
            "LeÃ³n",
            "Lleida",
            "Lugo",
            "MÃ¡laga",
            "Madrid",
            "Melilla",
            "Murcia",
            "Navarra",
            "Ourense",
            "Palencia",
            "Pontevedra",
            "Salamanca",
            "Santa Cruz de Tenerife",
            "Segovia",
            "Sevilla",
            "Soria",
            "Tarragona",
            "Teruel",
            "Valencia",
            "Valladolid",
            "Vizcaya",
            "Zamora",
            "Zaragoza",
            "(unassigned)",
            "Ã…land Islands",
            "Eastern Finland",
            "Lapland",
            "Oulu",
            "Southern Finland",
            "Western Finland",
            "(unassigned)",
            "(unassigned)",
            "Alsace",
            "Aquitaine",
            "Auvergne",
            "ÃŽle-de-France",
            "Brittany",
            "Burgundy",
            "Centre",
            "Champagne-Ardenne",
            "Corsica",
            "Franche-ComtÃ©",
            "Languedoc-Roussillon",
            "Limousin",
            "Lorraine",
            "Lower Normandy",
            "Midi-PyrÃ©nÃ©es",
            "Nord-Pas-de-Calais",
            "Pays-de-la-Loire",
            "Picardie",
            "Poitou-Charentes",
            "Provence-Alpes-CÃ´te-d\'Azur",
            "RhÃ´ne Alpes",
            "Upper Normandy",
            "(unassigned)",
            "England",
            "Northern Ireland",
            "Scotland",
            "Wales",
            "(unassigned)",
            "(unassigned)",
            "(unassigned)",
            "Achaea",
            "Aetolia-Acarnania",
            "Arcadia",
            "Argolis",
            "Arta",
            "Attica",
            "Boeotia",
            "Chalcidice",
            "Chania",
            "Chios",
            "Corfu",
            "Corinthia",
            "Cyclades",
            "Dodecanese",
            "Drama",
            "Euboea",
            "Evros",
            "Evrytania",
            "Florina",
            "Grevena",
            "Ilia",
            "Imathia",
            "Ioannina",
            "Irakleion",
            "Karditsa",
            "Kastoria",
            "Kavala",
            "Kefallinia",
            "Kilkis",
            "Kozani",
            "Laconia",
            "Larissa",
            "Lasithion",
            "Lefkada",
            "Lesbos",
            "Magnesia",
            "Messinia",
            "Mount Athos",
            "Pella",
            "Phocis",
            "Phthiotis",
            "Preveza",
            "Rethymnon",
            "Rhodope",
            "Samos",
            "Serres",
            "Thesprotia",
            "Thessaloniki",
            "Trikala",
            "Xanthi",
            "Zakynthos",
            "(unassigned)",
            "Å ibenik-Knin",
            "Bjelovar-Bilogora",
            "Brod-Posavina",
            "Dubrovnik-Neretva",
            "Istria",
            "Karlovac",
            "Koprivnica-KriÅ¾evci",
            "Krapina-Zagorje",
            "Lika-Senj",
            "MeÄ‘imurje",
            "Osijek-Baranja",
            "PoÅ¾ega-Slavonia",
            "Primorje-Gorski Kotar",
            "Sisak-Moslavina",
            "Split-Dalmatia",
            "VaraÅ¾din",
            "Virovitica-Podravina",
            "Vukovar-Srijem",
            "Zadar",
            "Zagreb",
            "Zagreb (city)",
            "(unassigned)",
            "BÃ¡cs-Kiskun",
            "BÃ©kÃ©s",
            "BÃ©kÃ©scsaba",
            "Baranya",
            "Borsod-AbaÃºj-ZemplÃ©n",
            "Budapest",
            "CsongrÃ¡d",
            "Debrecen",
            "DunaÃºjvÃ¡ros",
            "Eger",
            "FejÃ©r",
            "GyÅ‘r",
            "GyÅ‘r-Moson-Sopron",
            "HÃ³dmezÅ‘vÃ¡sÃ¡rhely",
            "Hajdu-Bihar",
            "Heves",
            "JÃ¡sz-Nagykun-Szolnok",
            "KaposvÃ¡r",
            "KecskemÃ©t",
            "KomÃ¡rom-Esztergom",
            "Miskolc",
            "Nagykanizsa",
            "NogrÃ¡d",
            "NyiregyhÃ¡za",
            "PÃ©cs",
            "Pest",
            "SalgÃ³tarjÃ¡n",
            "Somogy",
            "Sopron",
            "SzÃ©kesfehÃ©rvÃ¡r",
            "Szabolcs-SzatmÃ¡r-Bereg",
            "Szeged",
            "SzekszÃ¡rd",
            "Szolnok",
            "Szombathely",
            "TatabÃ¡nya",
            "Tolna",
            "Vas",
            "V"});
            this.comboBox3.Location = new System.Drawing.Point(111, 108);
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Size = new System.Drawing.Size(121, 21);
            this.comboBox3.TabIndex = 5;
            // 
            // SearchSetting
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(324, 286);
            this.Controls.Add(this.groupBox1);
            this.Name = "SearchSetting";
            this.Text = "SearchSetting";
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox comboBox3;
        private System.Windows.Forms.ComboBox comboBox2;
        private System.Windows.Forms.ComboBox comboBox1;
    }
}